### ISSUE TITLE
Question: roadmap and plans for the stable release

### ISSUE THREAD

**Issue by daniel-abramov** [livekit/rust-sdks#225]
I really like that LiveKit invests in Rust and that this Rust SDK exists! I was very excited to see that [many things are possible](https://github.com/livekit/rust-sdks/pull/216) even with the developer preview version. However, I also noticed that the API still has a lot of rough edges and that it's still more in an "alpha" state rather than in a production-grade state (also, the README says that).

So I just wanted to ask if there is a roadmap item that summarizes all open issues that must be resolved before the Rust SDK could be considered production-ready (or, at least, to prepare a "beta version" of the Rust SDK suitable for the use in production) and if there is any approximate ETA for that 🙂 (I know estimating big epics and milestones is indeed very hard)

**Comment by davidzhao** [comment]
Hey @daniel-abramov, Rust SDK should be fairly stable by now! We need to update the readme to remove developer preview from it. (I'll handle that soon).

We've built two SDKs on top of it by now (Python and Unity) and are fairly confident about the FFI interface and that the Rust core is flexible enough to support other language wrappers. Though it's possible we'll still make a couple of API changes here and there, it shouldn't be too significant.

Feel free to use it and let us know if you are seeing any issues. The Rust SDK is of importance to us because it'll be the foundation of all of our native SDKs in the future.
