### ISSUE TITLE
track muted / unmuted events should specify track type

### ISSUE THREAD

**Issue by cs50victor** [livekit/rust-sdks#287]
At the moment, Track Muted and Track Unmuted Events are used for both pausing and resuming videos or audio ( microphones ), but the TrackMuted & TrackUnmuted Event Structs don't specify which track got muted or unmuted

**Comment by theomonnom** [comment]
The TrackMuted and TrackUnmuted doesn't contain the Track struct but the TrackPublication.
This is because you can receive these events without being subscribed to these tracks.
If you're subscribed to the track, use this [method](https://github.com/livekit/rust-sdks/blob/decca08d51ae960c012fcbd49c42b3e65380d075/livekit/src/room/publication/mod.rs#L77) to get the current Track struct
